### ISSUE TITLE
TypeScript icon missing on npmjs

### ISSUE THREAD

**Issue by stefanpl** [farzher/fuzzysort#117]
For some reason, there is no `TS` icon indicating that the npm package has typings: https://www.npmjs.com/package/fuzzysort

This always had me not installing it 😮 

Where'd it go? 🤔

**Comment by revelt** [comment]
it's because root package.json is missing `types` key, it has to point to the type defs file's path, for example, see https://github.com/codsen/codsen/blob/main/packages/string-strip-html/package.json#L40 (for legacy) and couple lines above, ESM way https://github.com/codsen/codsen/blob/main/packages/string-strip-html/package.json#L36 from yours truly
