### ISSUE TITLE
How does this compare to https://github.com/krisk/Fuse?

### ISSUE THREAD

**Issue by cktang88** [farzher/fuzzysort#31]

**Comment by farzher** [comment]
fuse has more features, bugs, and unexpected behavior. this just does what you expect.

fuse uses levenshtein distance which allows for more typos and irrelevant characters to still return results.
this is a standard text editor file search (like sublime's).

for me, fuse wouldn't return results in the order i wanted https://github.com/krisk/Fuse/issues/89
which is why this exists and why it's called fuzzysort.

also this is way faster if performance matters. (i'd like to see a fuse benchmark)
