### ISSUE TITLE
Empty string match behavior

### ISSUE THREAD

**Issue by futurist** [farzher/fuzzysort#41]
When march an empty search string, the behavior is empty result.

Can add support to alter this behavior? Since the code must distinguish between empty keyword and non-empty keyword, and render result as highlighted or original item text, that add code complexity.

In addition, very good lib, thank you!

**Comment by nmussy** [comment]
I'm not sure what @futurist had in mind, but what I was thinking was an option to enable `fuzzysort.go` to return an unfiltered and unsorted array of results with an empty needle, just slicing it according to the `limit`.

**Comment by futurist** [comment]
What @nmussy mentioned is just what I mean. The empty string match nothing but should return ALL.

**Comment by MarcelloTheArcane** [comment]
You don't even need to go through fuzzysort if you want it to match all.

```js
function getResults (query, array, options) {
  return query === '' ? array : fuzzysort.go(query, array, options)
}
```

**Comment by viktor-ku** [comment]
The problem with example above is when you use Typescript you want to have all "results" to use one type across the board no matter what query really is. Because e.g. you have to render that list in the component. So you end up mapping over the targets array anyway to get the consistent objects.

**Comment by viktor-ku** [comment]
Ended up writing something like this

```ts
interface Dict {
    [key: string]: string;
}

function results<T>(data: Dict[]): KeyResults<T> {
    const arr: any = data.map(x => ({
        score: -1,
        target: x.value,
        indexes: [],
        obj: x
    }))

    arr.total = data.length

    return arr
}
```

**Comment by jnachtigall** [comment]
This is a problem for the consumer of the library - also for non-typescript, that is, normal JavaScript, because with `fuzzysort` you get results array with certain structure. If there is no filtering than the structure is totally different.

As @MarcelloTheArcane says you can use something like:
```js
const results = query === '' ? array : fuzzysort.go(query, array, options);
```

Then you pass down results to other parts of your app and they all - due to the different structure of `results` (either fuzzysort's structure or the consumer's normal array) - they all have to make case separation like:
```js
  const value =areTheResultsFiltered
    ? _.get(results, resultsKey)
    : _.get(results, `obj.resultsKey`);
```

This makes the code unnessesarily spaghetti and complex.

**Comment by farzher** [comment]
https://github.com/farzher/fuzzysort/commit/b04ff02245cdc14ca38c9f1e84450969e2b1f6d2
