### ISSUE TITLE
Suggestion for a style guide

### ISSUE THREAD

**Issue by ramlmn** [farzher/fuzzysort#8]
Can you add any style guide (maybe with eslint or whatever) so that other people could contribute with style consistency?

**Comment by farzher** [comment]
Good idea, but I don't think this project is big enough for that to matter. I'm not sure any contributions are even needed, the code is prettty good ;)

I'm closing this because I don't think it's an outstanding issue. Feel free contributing with whatever style you want. I'll pull and fix it myself if I have to.

I'll look into adding a style guide though, I'm pretty sure the current style is inconsistent. o:

**Comment by notlmn** [comment]
Maybe a good time to reconsider this.

If you are not too opinionated, I'd suggest https://github.com/xojs/eslint-config-xo-space, should be a quick addition too. I'd also suggest to setup CI on Travis to test and lint code.

What do you think!? I can send a quick PR if you want.
