### ISSUE TITLE
Return results with misspelling words (grammatically wrong written) or misprints

### ISSUE THREAD

**Issue by olegglocc** [farzher/fuzzysort#90]
I want to show words with incorrect writing or misprints in results. For example, with "pasttime" or "lollypop" nothing will be returned. 
![image](https://user-images.githubusercontent.com/53401889/142426826-b84b16eb-7850-41cd-982e-995ecb11ee9f.png)
![image](https://user-images.githubusercontent.com/53401889/142426885-243c587a-6a7c-4766-9636-93507f9a3ccd.png)

While "pastime" and "lollipop" are existing in targets.
![image](https://user-images.githubusercontent.com/53401889/142426952-aef66297-dca2-49c7-afa6-906996defd4f.png)
![image](https://user-images.githubusercontent.com/53401889/142427001-b62a5f98-ed75-4329-810a-5c1a33fe974f.png)

Of course with `allowTypo: true` option will find "pastime" with "pasitme" query, but it is not the same I mean. 

### Can you update your excellent library to **match grammatically wrong written words in query**? 

P.s. I don't know better way to do that. Maybe raise the score when character is mismatch but not ignore at all incorrect query word.

**Comment by farzher** [comment]
there's no plan to do this, since sublime text doesn't do this either.

you could try running the search like 8 times, once with each character missing, then merging the results? but that might give pretty bad results

[#58 ](https://github.com/farzher/fuzzysort/issues/58#issuecomment-602157414) defines a new version of `go` that accepts an array of searches and merges the results
